export const INIT_GET_USER = "INIT_GET_USER";
export const UPDATE_USER = "UPDATE_USER";
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export const SET_GUESS = "SET_GUESS";
export const UPDATE_APP_COLOR = "UPDATE_APP_COLOR";
export const CHANGE_WISHLIST_COLOR = "CHANGE_WISHLIST_COLOR";
export const CHANGE_WISHLISTS_DIRECTION = "CHANGE_WISHLISTS_DIRECTION";